class Premium {
  int? id;
  int? userSenderId;
  int? userReciverId;
  int? isVeriefy;
  String? createdAt;
  String? updateAt;
  int? isDeleted;
  int? isPremium;
  String? isNotJoint;
  int? loginType;
  String? socialToken;
  String? phoneCode;
  int? mobileNumber;
  String? email;
  String? password;
  String? name;
  int? isVerfied;
  String? socialId;
  int? countryId;
  String? language;
  String? city;
  String? otp;
  String? profileImage;
  String? lastName;
  String? gender;
  int? smsNotfication;
  String? emergencyContact;
  String? messengerContact;
  String? country;
  String? address;
  int? zipCode;
  int? isPrivacy;
  double? latitude;
  double? longitude;
  int? isSendNotfication;

  Premium.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userSenderId = json['userSenderId'];
    userReciverId = json['userReciverId'];
    isVeriefy = json['isVeriefy'];
    createdAt = json['createdAt'];
    updateAt = json['updateAt'];
    isDeleted = json['isDeleted'];
    isPremium = json['isPremium'];
    isNotJoint = json['isNotJoint'];
    loginType = json['loginType'];
    socialToken = json['socialToken'];
    phoneCode = json['phoneCode'];
    mobileNumber = json['mobileNumber'];
    email = json['email'];
    password = json['password'];
    name = json['name'];
    isVerfied = json['isVerfied'];
    socialId = json['socialId'];
    countryId = json['countryId'];
    language = json['language'];
    city = json['city'];
    otp = json['otp'];
    profileImage = json['profileImage'];
    lastName = json['lastName'];
    gender = json['gender'];
    smsNotfication = json['smsNotfication'];
    emergencyContact = json['emergencyContact'];
    messengerContact = json['messengerContact'];
    country = json['country'];
    address = json['address'];
    zipCode = json['zipCode'];
    isPrivacy = json['isPrivacy'];
    latitude = double.parse(json['Latitude'].toString());
    longitude = double.parse(json['Longitude'].toString());
    isSendNotfication = json['isSendNotfication'];
  }
}
