// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkbFHZXMjvYLEmNcVYifNmh6atP-geFeM',
    appId: '1:210720504820:web:53dabd26e7b877854c57a1',
    messagingSenderId: '210720504820',
    projectId: 'find-me-744f4',
    authDomain: 'find-me-744f4.firebaseapp.com',
    storageBucket: 'find-me-744f4.appspot.com',
    measurementId: 'G-KQFYDXVZ3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFGY4owOBfwzw_ER0hBW9NNgdBuacOlE',
    appId: '1:210720504820:android:8a4bcca34215e1574c57a1',
    messagingSenderId: '210720504820',
    projectId: 'find-me-744f4',
    storageBucket: 'find-me-744f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdx-lkwG-a1onjrh-2hUVbQT7ONhpv_2c',
    appId: '1:210720504820:ios:3d7d452f9b98b6634c57a1',
    messagingSenderId: '210720504820',
    projectId: 'find-me-744f4',
    storageBucket: 'find-me-744f4.appspot.com',
    iosBundleId: 'com.pets.findMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdx-lkwG-a1onjrh-2hUVbQT7ONhpv_2c',
    appId: '1:210720504820:ios:797d4277929a463b4c57a1',
    messagingSenderId: '210720504820',
    projectId: 'find-me-744f4',
    storageBucket: 'find-me-744f4.appspot.com',
    iosBundleId: 'com.pets.findMe.RunnerTests',
  );
}
